name: Package Mac
on:
  push:
    tags: '*'

jobs:
  pre-release:
    name: Pre Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-latest]
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Change Log Mac
        if: matrix.os == 'macOS-latest'
        run: |
          chmod +x changelog.sh
          ./changelog.sh

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
          fi
          go get fyne.io/fyne/cmd/fyne

      - name: Package App Mac
        if: matrix.os == 'macOS-latest'
        run: |
          chmod +x build.sh
          ./build.sh
          mkdir -p dist 
          mv "Blu.app" dist/
          cd dist
          npx create-dmg Blu.app | echo "done"
          rm -rf "Blu.app"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          files: 'dist/**'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
